# -*- coding: utf-8 -*-
'''
Sample evaluation: Step-Two

This module calculates root mean squared deviation of each prediction variable, predicted by the model using a sample
parameter set, from the predictions with a reference parameter sample. The predictions are generated by the model in the
first step of the sample evaluation and stored in binary file as basin scale summary monthly time series. The samples
are taken using the SAFE1.8 Toolbox in MatLab using Morris (1991) sampling strategy for EET SA method. Two sampling
parameters are important for this module to identify the reference sample from the sample set which are (i) Number of EE
to be used (r) in EET analysis and (ii) Number of parameters to be considered (M) was 24; other sampling parameters are
not relevant to this module. Every ((M+1) * i; where i ε {0, 1, 2, ... r-1})th  sample is considered as the reference
sample for the next r samples.

Algorithm:
    Step-1: assign r and M
    Step-2: gather information regarding the prediction variables and the address of summary timeseries at model runs
            with samples (output of step-one of sample evaluation). This information can be readily available in the
            configuration file used in the step-one of sample evaluation.
    Step-3: read binary time-series file for each variable, reconstruct the timeseries
    Step-4: find the reference sample and reference time-series
    Step-5: compute the root mean squared deviation (rmsd), set rmsd of the reference sample to zero
    Step-6: sort the result according to the sample appearance in the sample file and save the result
    Notes : In addition to root mean squared deviation, other useful statistics can be calculated following the same
            algorithm; however, in case of other statistics, it is not necessary to assign zero to the reference sample.

Definition of Root Mean Squared Deviation (rmsd):
        rmsd = sqrt ( mean ( (pred_ref - pred_sam) ** 2) );
        where pred_ref is the prediction time series with reference sample and pred_sam is the prediction time series
        with the current sample

Inputs:
    r                   : (int) Number of EEs (a parameter used in sampling)
    M                   : (int) Number of model parameters (a parameter used in sampling)
    config_filename     : (string) path of configuration file
    output_directory    : (string) path of output directory
    start_year          : (int; optional; default value: -1) start year of time series
    end_year            : (int; optional; default value: -1) end year of time series. if star and end year is provided,
                          time series will be truncated only to these time-limits
'''

r = 400
M = 24
working_directory = 'F:/mhasan/experiments/GlobalCDA/SA_mississippi/replication_three/'
config_filename = 'config/configuration_eet_sample_evaluation_mississippi_step_one.txt'
output_directory = 'output_step_two/anomaly'
start_year = -1
end_year = -1
flag_compute_anomaly = True



# import required modules and classes
import os, numpy as np
from core.configuration import Configuration
from wgap.wgapio import WaterGapIO
from wgap.watergap import WaterGAP
from utilities.fileio import FileInputOutput as io
from datetime import datetime


def compute_rmsd(ts1:np.ndarray, ts2:np.ndarray)->np.ndarray:
    '''
    The method computes the root mean squared deviation (rmsd) between two time series of same length.
    :param ts1: (1d numpy array) First time-series
    :param ts2: (1d numpy array) Second time-series
    :return: (float) root of mean squared deviation
    '''
    return np.sqrt(np.mean((ts1-ts2)**2))

def construct_time_series(data, sample_id, basin_id, start_year=-1, end_year=-1):
    '''
    This method constructs 1d time-series from the data. First it find data for specified basin and for specified
    sample and then sort data according to the years. Finally, it constructs the time-series with monthly data of
    all years. If the start and end year is specified, data will be truncated to limit the output time-series within
    those years.

    :param data: (ndarray) input 2d data having 15 columns containing sample id, basin id, year, and 12 monthly values
    :param sample_id: (int) sample id
    :param basin_id:  (int) basin id or cell number
    :param start_year: (int; optional; default value = -1) start year, if provided this would be the lower temporal limit
    :param end_year:  (int; optional; default value = -1) end year, if provided this would be the upper temporal limit
    :return: (1d numpy array) time series for the current sample for specified basin
    '''

    # step: filter data using basin id and sample id. crop data from 3rd column till the end column
    #       [expected shape is (nyear, 13)]
    ndx = np.where((data[:, 0] == sample_id) & (data[:, 1] == basin_id))
    d = data[ndx][:, 2:]

    # step: truncate data according to year range, if start and end year is given
    if start_year > 1901 and end_year > 1901 and start_year <= end_year:
        ndx = np.where((d[:,0]>=start_year) & (d[:,0] <=end_year))
        d = d[ndx]

    # step: sort the data according to the year column. crop data from 2nd column till the end column
    ndx = np.argsort(d[:, 0])
    d = d[ndx][:, 1:]

    return d.flatten()


def build_prediction_time_series(data, sample_id):
    """
    This method constructs 1d time-series from the data. First it find data for specified sample and then sort data
    according to the years. Finally, it constructs the time-series with monthly data of all years.

    :param data: (ndarray) input 2d data having 15 columns containing sample id, basin id, year, and 12 monthly values
    :param sample_id: (int) sample id
    :return: (1d numpy array) time series for the current sample for specified basin
    """

    # step: filter data using basin id and sample id. crop data from 3rd column till the end column
    #       [expected shape is (nyear, 13)]
    ndx = np.where(data[:, 0] == sample_id)
    d = data[ndx][:, 2:]

    # step: sort the data according to the year column. crop data from 2nd column till the end column
    ndx = np.argsort(d[:, 0])
    d = d[ndx][:, 1:]

    return d.flatten()


def main():
    # step: fetch global variables
    global r, M, working_directory, config_filename, output_directory, start_year, end_year, flag_compute_anomaly

    # step: compute total number of samples
    nsample = r * (M + 1)

    # step: read configuration file
    os.chdir(working_directory)
    config = Configuration.read_configuration_file(config_filename)
    if not config and config.is_okay(): return False

    # step: read the target input data directory and file endian type
    data_directory = config.output_directory
    file_endian = WaterGAP.output_endian_type

    # step: for each simulation variable follow next steps
    for var in config.sim_variables:
        print('Processing has started for variable: %s' % var.varname)

        # step: generate data filename
        filename = '%s.15.unf0'%var.varname             # for monthly time series
        filename = os.path.join(data_directory, filename)

        # step: read binary data from the data-file
        data = WaterGapIO.read_unf(filename, file_endian=file_endian)
        if not type(data) is np.ndarray: return False

        # step: check if the number of basins (or cells) is consistent with variable properties
        nbasin = 0
        if var.group_stats: nbasin = len(var.cell_groups)
        else:
            grp_member = []
            for group in var.cell_groups: grp_member += group
            nbasin = len(np.unique(grp_member))

        basins = np.unique(data[:,1])
        if basins.size != nbasin: return False

        results_rmsd = []
        # step: for each basin/cell, compute rmsd with each sample and store the results
        for bid in basins:
            print('\tcurrent basin no.: %d' %bid, end='', flush=True)
            t = datetime.now()

            time_series_ref = None          # reference time series

            # step: crop basin specific predictions from data
            ndx = np.where(data[:, 1] == bid)
            basin_data = data[ndx]
            if start_year > 1901 and end_year > 1901 and start_year <= end_year:
                ndx = np.where((basin_data[:, 2] >= start_year) & (basin_data[:, 2] <= end_year))
                basin_data = basin_data[ndx]
            # ... end [of data cropping]

            # step: for each sample, construct time-series and compute rmsd with the current time-series and reference
            #       time-series. if the current sample is a reference sample, reference time-series must be updated
            #       with the current time-series and rmsd should be assign to zero
            for sid in range(nsample):
                time_series_curr = build_prediction_time_series(basin_data, sid)
                if flag_compute_anomaly: time_series_curr = time_series_curr - time_series_curr.mean()
                if sid%(M+1) == 0:
                    # if the current sample should be considered as a reference, set rmsd to zero and update
                    # the reference time-series with current time-series
                    rmsd = 0
                    time_series_ref = time_series_curr
                else: rmsd = compute_rmsd(time_series_curr, time_series_ref)

                results_rmsd.append([bid, sid, rmsd])

            # display how much time required for each basin
            tdif = datetime.now() - t
            total_t = tdif.seconds + tdif.microseconds / 10**6
            print(' [total time: %f seconds]' % total_t)

        # step: write results into output file
        if flag_compute_anomaly: filename = os.path.join(output_directory, 'anomaly_%s_rmsd.csv' % var.varname.lower())
        else: filename = os.path.join(output_directory, '%s_rmsd.csv' % var.varname.lower())
        # np.savetxt(filename, results_rmsd, delimiter=',')
        succeed = io.write_flat_file(filename, results_rmsd, separator=',')
    return True

if __name__ == '__main__': main()
