fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')
p = ax.scatter(x, y, z, c=c, cmap=plt.get_cmap('winter'), edgecolors='face', s=30, vmin=0.85, vmax=1.0)
cbar = plt.colorbar(p, ticks=[0.85, 0.90, 0.95, 1.0])
cbar.ax.set_ylabel('kge (twsv)', rotation=90, fontsize=20)
cbar.outline.set_linewidth(0.6)
cbar.ax.get_yaxis().labelpad = -75
cbar.ax.get_yaxis().set_ticks_position('right')
#cbar.ax.get_yaxis().tick_left()
plt.show()